// Auto-generated by scripts/gen-installer-urls.ps1 - do not edit manually.
internal static class InstallerVersion
{
    internal const string VERSION_NAME = "0.9.6";
    internal const int VERSION_CODE = 15;
}
