// Auto-generated by scripts/gen-installer-urls.ps1 - do not edit manually.
internal static class InstallerUrls
{
    internal const string GithubOwner = "pgraafland356-debug";
    internal const string GithubRepo = "MiddinInnovatie";
    internal const string UpdateFeedUrl = "https://raw.githubusercontent.com/pgraafland356-debug/MiddinInnovatie/main/releases/latest.json";
    internal const string ReleasesPageUrl = "https://github.com/pgraafland356-debug/MiddinInnovatie/releases";
}
