# Generates desktop/installer/InstallerUrls.cs and InstallerVersion.cs from gradle + app/build.gradle.kts.
$ErrorActionPreference = "Stop"
$repo = Split-Path -Parent $PSScriptRoot
. (Join-Path $PSScriptRoot "read-github-update-config.ps1")
$config = Get-MiddinGithubUpdateConfig -Root $repo

$appGradle = Get-Content (Join-Path $repo "app\build.gradle.kts") -Raw
$versionName = "0.9.4"
$versionCode = 13
if ($appGradle -match 'versionName\s*=\s*"([^"]+)"') {
    $versionName = $Matches[1]
}
if ($appGradle -match 'versionCode\s*=\s*(\d+)') {
    $versionCode = [int]$Matches[1]
}

$urlsOut = Join-Path $repo "desktop\installer\InstallerUrls.cs"
$urlsContent = @"
// Auto-generated by scripts/gen-installer-urls.ps1 - do not edit manually.
internal static class InstallerUrls
{
    internal const string GithubOwner = "$($config.Owner)";
    internal const string GithubRepo = "$($config.Repo)";
    internal const string UpdateFeedUrl = "$($config.FeedUrl)";
    internal const string ReleasesPageUrl = "$($config.ReleasesUrl)";
}
"@

$versionOut = Join-Path $repo "desktop\installer\InstallerVersion.cs"
$versionContent = @"
// Auto-generated by scripts/gen-installer-urls.ps1 - do not edit manually.
internal static class InstallerVersion
{
    internal const string VERSION_NAME = "$versionName";
    internal const int VERSION_CODE = $versionCode;
}
"@

Set-Content -Path $urlsOut -Value $urlsContent.TrimEnd() -Encoding UTF8
Set-Content -Path $versionOut -Value $versionContent.TrimEnd() -Encoding UTF8
Write-Host "Generated $urlsOut" -ForegroundColor Green
Write-Host "Generated $versionOut ($versionName / $versionCode)" -ForegroundColor Green
