# Generates desktop/installer/InstallerUrls.cs from gradle.properties.
$ErrorActionPreference = "Stop"
$repo = Split-Path -Parent $PSScriptRoot
. (Join-Path $PSScriptRoot "read-github-update-config.ps1")
$config = Get-MiddinGithubUpdateConfig -Root $repo

$out = Join-Path $repo "desktop\installer\InstallerUrls.cs"
$content = @"
// Auto-generated by scripts/gen-installer-urls.ps1 - do not edit manually.
internal static class InstallerUrls
{
    internal const string GithubOwner = "$($config.Owner)";
    internal const string GithubRepo = "$($config.Repo)";
    internal const string UpdateFeedUrl = "$($config.FeedUrl)";
    internal const string ReleasesPageUrl = "$($config.ReleasesUrl)";
}
"@

Set-Content -Path $out -Value $content.TrimEnd() -Encoding UTF8
Write-Host "Generated $out" -ForegroundColor Green
